if (NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required.")
endif()

if (NOT DEFINED INCLUDE_ROOT)
    message(FATAL_ERROR "INCLUDE_ROOT is required.")
endif()

set(header_paths "")
if (DEFINED HEADER_PATHS AND NOT HEADER_PATHS STREQUAL "")
    string(REPLACE "||" ";" header_paths "${HEADER_PATHS}")
endif()

set(script_includes "")
set(register_entries "")
set(unregister_entries "")

foreach(script_header_path IN LISTS header_paths)
    file(RELATIVE_PATH script_header "${INCLUDE_ROOT}" "${script_header_path}")

    get_filename_component(script_stem "${script_header}" NAME_WE)
    file(READ "${script_header_path}" script_header_contents)

    if (NOT script_header_contents MATCHES "Register${script_stem}Script[ \t\r\n]*\\(")
        continue()
    endif()

    if (NOT script_header_contents MATCHES "UnRegister${script_stem}Script[ \t\r\n]*\\(")
        continue()
    endif()

    list(APPEND script_includes "#include <${script_header}>")

    set(script_prefix "")

    if (script_header_contents MATCHES "ScriptName[ \t\r\n]*=[ \t\r\n]*\"([^\"]+)\"")
        set(script_name "${CMAKE_MATCH_1}")
        string(FIND "${script_name}" "::" last_namespace_separator REVERSE)
        if (NOT last_namespace_separator EQUAL -1)
            string(SUBSTRING "${script_name}" 0 ${last_namespace_separator} script_namespace)
            set(script_prefix "${script_namespace}::")
        endif()
    elseif (script_header_contents MATCHES "namespace[ \t\r\n]+([A-Za-z_][A-Za-z0-9_:]*)[ \t\r\n]*\\{")
        set(script_prefix "${CMAKE_MATCH_1}::")
    endif()

    list(APPEND register_entries "        &${script_prefix}Register${script_stem}Script,")
    list(APPEND unregister_entries "        &${script_prefix}UnRegister${script_stem}Script,")
endforeach()

list(SORT script_includes)
list(SORT register_entries)
list(SORT unregister_entries)

set(script_includes_text "")
foreach(script_include IN LISTS script_includes)
    string(APPEND script_includes_text "${script_include}\n")
endforeach()

set(register_entries_text "")
foreach(register_entry IN LISTS register_entries)
    string(APPEND register_entries_text "${register_entry}\n")
endforeach()

set(unregister_entries_text "")
foreach(unregister_entry IN LISTS unregister_entries)
    string(APPEND unregister_entries_text "${unregister_entry}\n")
endforeach()

set(register_calls_text "")
foreach(register_entry IN LISTS register_entries)
    string(REGEX REPLACE "^        &" "    " register_call "${register_entry}")
    string(REGEX REPLACE ",$" "(_app);" register_call "${register_call}")
    string(APPEND register_calls_text "${register_call}\n")
endforeach()

set(unregister_calls_text "")
foreach(unregister_entry IN LISTS unregister_entries)
    string(REGEX REPLACE "^        &" "    " unregister_call "${unregister_entry}")
    string(REGEX REPLACE ",$" "(_app);" unregister_call "${unregister_call}")
    string(APPEND unregister_calls_text "${unregister_call}\n")
endforeach()

set(generated_source
"// This file is generated by CMake. Do not edit by hand.
#pragma once

${script_includes_text}

inline void RegisterGeneratedScripts(Canis::App &_app)
{
${register_calls_text}}

inline void UnRegisterGeneratedScripts(Canis::App &_app)
{
${unregister_calls_text}}
")

if (EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" existing_source)
else()
    set(existing_source "")
endif()

if (NOT existing_source STREQUAL generated_source)
    file(WRITE "${OUTPUT_FILE}" "${generated_source}")
endif()
